export const exams = [
  {
    id: 'sat',
    name: 'SAT',
    description: 'US college admissions — 400 to 1600',
    color: '#6366f1',
    icon: '📐',
    scoreRange: '400–1600',
    scoringNote: 'Math + Evidence-Based Reading & Writing',
    avgScore: 1050,
    maxScore: 1600,
    audience: 'US high school students applying to college',
    adminBody: 'College Board',
    frequency: 'Multiple times per year',
    resultDelay: 'Score released ~2–3 weeks after test',
  },
  {
    id: 'act',
    name: 'ACT',
    description: 'US college admissions — 1 to 36',
    color: '#06b6d4',
    icon: '✏️',
    scoreRange: '1–36',
    scoringNote: 'English, Math, Reading, Science composite',
    avgScore: 21,
    maxScore: 36,
    audience: 'US high school students applying to college',
    adminBody: 'ACT, Inc.',
    frequency: 'Multiple times per year',
    resultDelay: 'Score released ~2–8 weeks after test',
  },
  {
    id: 'gre',
    name: 'GRE',
    description: 'US graduate school admissions — 130 to 170',
    color: '#a855f7',
    icon: '🎓',
    scoreRange: '130–170 per section',
    scoringNote: 'Verbal Reasoning, Quantitative Reasoning, Analytical Writing',
    avgScore: 150,
    maxScore: 170,
    audience: 'Students applying to US graduate programs',
    adminBody: 'ETS (Educational Testing Service)',
    frequency: 'Year-round, on demand',
    resultDelay: 'Unofficial scores immediately; official in 10–15 days',
  },
  {
    id: 'gmat',
    name: 'GMAT',
    description: 'MBA admissions — 205 to 805',
    color: '#f59e0b',
    icon: '💼',
    scoreRange: '205–805',
    scoringNote: 'Verbal, Quantitative, Data Insights sections',
    avgScore: 550,
    maxScore: 805,
    audience: 'Students applying to MBA and business programs',
    adminBody: 'GMAC (Graduate Management Admission Council)',
    frequency: 'Year-round, on demand',
    resultDelay: 'Unofficial scores immediately; official in ~7 days',
  },
  {
    id: 'lsat',
    name: 'LSAT',
    description: 'US law school admissions — 120 to 180',
    color: '#ef4444',
    icon: '⚖️',
    scoreRange: '120–180',
    scoringNote: 'Logical Reasoning, Analytical Reasoning, Reading Comprehension',
    avgScore: 152,
    maxScore: 180,
    audience: 'Students applying to US law schools (JD programs)',
    adminBody: 'LSAC (Law School Admission Council)',
    frequency: '9 times per year',
    resultDelay: 'Score released ~3–4 weeks after test',
  },
  {
    id: 'gcse',
    name: 'GCSE',
    description: 'UK secondary qualification — grade 1 to 9',
    color: '#34d399',
    icon: '🏫',
    scoreRange: 'Grade 1–9 (9 is highest)',
    scoringNote: 'Graded 1–9; grade 4 is standard pass, grade 5 is strong pass',
    avgScore: 5,
    maxScore: 9,
    audience: 'UK students aged 14–16, usually Year 10–11',
    adminBody: 'AQA, Edexcel, OCR, WJEC',
    frequency: 'Annual — exams in May/June, results in August',
    resultDelay: 'Results released third Thursday of August',
  },
  {
    id: 'a-levels',
    name: 'A-Levels',
    description: 'UK advanced qualification — grades E to A*',
    color: '#ec4899',
    icon: '📚',
    scoreRange: 'Grades E, D, C, B, A, A* (A* is highest)',
    scoringNote: 'Each grade maps to UCAS tariff points (A* = 56, A = 48, B = 40...)',
    avgScore: 'B',
    maxScore: 'A*',
    audience: 'UK students aged 16–18, usually Year 12–13',
    adminBody: 'AQA, Edexcel, OCR, WJEC, CIE',
    frequency: 'Annual — exams in May/June, results in August',
    resultDelay: 'Results released second Thursday of August (Aug 14, 2026)',
  },
];

export const howItWorks = [
  {
    step: 1,
    title: 'Enter your score',
    description: 'Type in your raw score or use the slider. Works for every section of every supported exam.',
    icon: '✏️',
  },
  {
    step: 2,
    title: 'We calculate your percentile',
    description: 'We compare your score against real test-taker data from official sources — updated for 2026.',
    icon: '📊',
  },
  {
    step: 3,
    title: 'Understand where you stand',
    description: 'See your exact percentile, rank context, and a full score breakdown table. No signup needed.',
    icon: '🎯',
  },
];

export const stats = [
  { value: '7',    label: 'Exams covered' },
  { value: '100%', label: 'Free forever' },
  { value: '2026', label: 'Data updated' },
  { value: '40+',  label: 'Countries' },
];

export const testimonials = [
  {
    name: 'Marcus T.',
    role: 'SAT — Class of 2026',
    quote: 'Finally a clean tool that just tells me my percentile without making me sign up for anything. Bookmarked.',
    image: '👨‍🎓',
  },
  {
    name: 'Priya S.',
    role: 'GRE — applying to Stanford',
    quote: 'I checked my GRE score here the moment results dropped. The percentile breakdown by section is really useful.',
    image: '👩‍💻',
  },
  {
    name: 'Jamie R.',
    role: 'A-Levels — UK, 2026',
    quote: 'Helped me understand what my predicted grades mean in terms of UCAS points before I even got my results.',
    image: '🎓',
  },
];
